CalendarApp/Controllers/CalendarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Globalization;
using CalendarApp.Models;

namespace CalendarApp.Controllers
{
    public class CalendarController : Controller
    {
        public IActionResult Index()
        {
            DateTime today = DateTime.Today;

            return RedirectToAction("ShowCalendar", new { year = DateTime.Today.Year, month = DateTime.Today.Month });
        }

        //gets current date
        private DateTime GetCurrentDate()
        {
            return DateTime.Today;
        }

        private int[] GetAllDaysInMonth(int year, int month) 
        {
            Enumerable.Range(1, DateTime.DaysInMonth(year, month)).ToArray();

            //var date = GetCurrentDate();
            //var date = new DateTime(year, month, 1);
            var dates = new int[DateTime.DaysInMonth(year, month)];

            for (int i = 0; i < dates.Length; i++) {
                dates[i] = i + 1;
            }

            return dates;
        }

        private DateTime[] GetAllDatetimesInMonth(int year, int month)
        {
            var dates = new DateTime[DateTime.DaysInMonth(year, month)];
            for (int i = 0; i < dates.Length; i++)
            {
                dates[i] = new DateTime(year, month, i+1);
            }
            return dates;
        }

        private DateTime[] GenerateOffsetBefore(int OffsetLenght, int currentYear, int currentMonth)
        {
            var offsetBefore = new DateTime[OffsetLenght];

            //gets dates in previous month
            DateTime[] daysPrevMonth;
            if (currentMonth > 1)
            {
                daysPrevMonth = GetAllDatetimesInMonth(currentYear, currentMonth - 1);
            }
            else
            {
                daysPrevMonth = GetAllDatetimesInMonth(currentYear - 1, 12);
            }

            //takes necessary amount from previous month
            for (int i = 0; i < OffsetLenght; i++)
            {
                offsetBefore[i] = daysPrevMonth[daysPrevMonth.Length - (i + 1)];
            }
            Array.Reverse(offsetBefore);

            return offsetBefore;
        }

        private DateTime[] GenerateOffsetAfter(int OffsetLenght, int currentYear, int currentMonth)
        {
            var offsetAfter = new DateTime[OffsetLenght];

            //gets dates in next month
            DateTime[] daysNextMonth;
            if (currentMonth != 12)
            {
                daysNextMonth = GetAllDatetimesInMonth(currentYear, currentMonth + 1);
            }
            else
            {
                daysNextMonth = GetAllDatetimesInMonth(currentYear + 1, 1);
            }

            //takes necessary amount from next month

            for (int i = 0; i < OffsetLenght; i++)
            {
                offsetAfter[i] = daysNextMonth[i];
            }

            return offsetAfter;
        }



        public RedirectToActionResult ShowPrevious(int currentYear, int currentMonth) {
            int prevYear = currentYear;
            int prevMonth = currentMonth;
            if (currentMonth == 1) {
                prevMonth = 12;
                prevYear = currentYear - 1;
            }
            else
            {
                prevMonth = currentMonth - 1;
            }
            return RedirectToAction("ShowCalendar", new { _year = prevYear, _month = prevMonth, _day = 1});
            //ShowCalendar(prevYear, prevMonth);
        }

        public RedirectToActionResult ShowNext(int currentYear, int currentMonth){
            int nextYear = currentYear;
            int nextMonth = currentMonth;
            if (currentMonth == 12)
            {
                nextMonth = 1;
                nextYear = currentYear + 1;
            }
            else
            {
                nextMonth = currentMonth + 1;
            }
            return RedirectToAction("ShowCalendar", new { _year = nextYear, _month = nextMonth, _day = 1});
            //ShowCalendar(nextYear, nextMonth);
        }
        //generates the calendar array and passes it to the view
        //will start with creating an array either 28 or 35 members long
        //1. add the required offset if the month does not start on Sunday
        //2. add all days that are relevant to the current month
        //3. add offset for the remaining positions in the array

        //4. replace offset with last days of the previous month, and first days of the next month
        public IActionResult ShowCalendar(int _year, int _month, int _day)
        {
            //string rawDate = _year + _month + _day;
            //DateTime selectedDate = DateTime.ParseExact(rawDate, "yyyy MM dd", CultureInfo.InvariantCulture);

            DateTime selectedDate = new DateTime(_year, _month, _day);

            int year = selectedDate.Year;
            int month = selectedDate.Month;
            int day = selectedDate.Day;

            //DateTime selectedDate = new DateTime(year, month, day);
            //gets the weekday of the first day in the month
            DateTime[] offsetBeforeDates;
            DateTime[] currentMonthDates;
            DateTime[] offsetAfterDates;

            DateTime firstDayOfMonth = new DateTime(year, month, 1);
            int firstWeekDay = (int)firstDayOfMonth.DayOfWeek;

            //generate offset before
            // 0 in DateTime.DayOfWeek represents Sunday if cast to integer
            if (firstWeekDay != 0)
            {
                offsetBeforeDates = GenerateOffsetBefore(firstWeekDay, year, month);
            }
            else offsetBeforeDates = new DateTime[0];

            //generate current month dates
            currentMonthDates = GetAllDatetimesInMonth(year, month);

            //generate offset after
            int offsetAfterLenght = 42 - (offsetBeforeDates.Length + currentMonthDates.Length);
            if (offsetAfterLenght > 0)
            {
                offsetAfterDates = GenerateOffsetAfter(offsetAfterLenght, year, month);
            }
            else offsetAfterDates = new DateTime[0];

            //ViewData["OffsetBefore"] = offsetBeforeDates;
            //ViewData["OffsetAfter"] = offsetAfterDates;
            //ViewData["CurrentMonthDates"] = currentMonthDates;
            //ViewData["Date"] = selectedDate;

            var m = new CalendarDates {
                offsetBeforeDates = offsetBeforeDates,
                currentMonthDates = currentMonthDates,
                offsetAfterDates = offsetAfterDates,
                selectedDate = selectedDate
            };

            return View(m);
        }
    }
}

CalendarApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CalendarApp.Models;

namespace CalendarApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Test()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CalendarApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    DateTime today = DateTime.Today;
}

<div>
    <ul>
        <li>
            <a asp-controller="Calendar" asp-action="ShowCalendar" asp-route-_year="@today.Year" asp-route-_month="@today.Month" asp-route-_day="@today.Day">Calendar App</a>
        </li>
        <li>
            <a asp-controller="Home" asp-action="Test">Testing Grounds</a>
        </li>
       
    </ul>
        
</div>
@*<div>
    <partial name="_ShowDay">
</div>*@

CalendarApp/Views/Home/Test.cshtml
<!DOCTYPE html>

<script>

    const locationApiKey = "3c65c4dc2c25497c9dfbf0091c1b0740";
    const weatherApiKey = "da16ce4bf753424c126bd24de2ef7d42";


    const locationRoute = "https://api.ipgeolocation.io/ipgeo?apiKey=";
    const weatherRoute = "https://api.openweathermap.org/data/2.5/weather?q=";

    const city = "Prague";
    //http accept
    //swagger.io

    //tfs - practice manual and automatic merging
    //get a dev account

    //CRM + TFS - keep questions for future sessions

    //get approval from Simona to Anne Kwast on 1st of april there is a big planning meeting for CRM in Frankfurt

    const weatherRequestweatherRoute = weatherRoute + city + "&appid=" + weatherApiKey;
    const locationRequestRoute = locationRoute + locationApiKey;

    function masterWeatherRequest(apiWeatherRoute) {
        getWeather(apiWeatherRoute).then(function (result) {
            let json = JSON.parse(result);
            console.log(json.main.temp)
            console.log(json.weather[0].main)
            let temperature = (json.main.temp - 273).toFixed(1);
            document.getElementById("wInfo").innerHTML = "Weather: " +  json.weather[0].main + ", the temperature is: " + temperature + " Celsius";
        })
    }

    function masterLocationRequest(apiLocationRoute) {
        getLocation(apiLocationRoute).then(function (result) {
            let json = JSON.parse(result);
            console.log("You are in " + json.city);
            document.getElementById("lInfo").innerHTML = json.city;
        })
    }

    function getLocation(apiLocationRoute) {
        return new Promise(function (resolve, reject){
            let request = new XMLHttpRequest();
            request.open("GET", apiLocationRoute, true);
            request.onload = function () {
                if (request.status == 200) {
                    resolve(request.responseText);
                }
                else {
                    reject(Error("Error getting location"));
                }
            };
            request.onerror = function () {
                reject(Error("Network Error"));
            };

            request.send();
        })
    }

    function getWeather(apiWeatherRoute) {
        return new Promise(function (resolve, reject) {
            //send the http request here
            let request = new XMLHttpRequest();
            request.open("GET", apiWeatherRoute, true);
            request.onload = function () {
                //check if server replied with status OK
                if (request.status == 200) {
                    resolve(request.responseText);
                }
                else {
                    reject(Error("Error getting weather info"));
                }
            };
            request.onerror = function () {
                reject(Error("Network Error"));
            };

            request.send();
        })
    }

    function printResponse(responseText) {
        console.log(responseText);
    }
</script>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Testing Grounds</title>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
</head>
<body>
    <h1>Welcome to the testing grounds.</h1>
    <div>
        <button type="button" title="Get Weather" onclick="masterWeatherRequest(weatherRequestweatherRoute)">Weather</button>
        <p id="wInfo">Weather goes here</p>

        <button type="button" title="Get Location" onclick="masterLocationRequest(locationRequestRoute)">Location</button>
        <p id="lInfo">Location goes here</p>
    </div>
</body>
</html>

@*api.openweathermap.org/data/2.5/weather?q={city name},{country code}*@
@*api.openweathermap.org/data/2.5/weather?q=Prague,CZ*@

CalendarApp/Views/Home/_ShowDay.cshtml
@*@model CalendarApp.Models.DateAppoointment;   *@
@{
    var day = ViewData["Day"];
    var month = ViewData["MonthName"];
    var year = ViewData["Year"];
}

<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>


<div class="dayView">
    <div class="dayViewHeader" id="dayViewHeader">
        @*<h3 id="dayHeader">@month @day, @year</h3>
            <button type="button" onclick="displayForm()" runat="client" class="add" title="Add Appointment"></button>*@
    </div>
    <div id="appointmentContainer">Empty</div>

</div>


<h2>Example 2:</h2>
<form id="second_form" method="post" action="">
    <div>
        <label for="fname">First Name:</label>
        <input type="text" id="fname" name="fname">
    </div>
    <div>
        <label for="lname">Last Name:</label>
        <input type="text" id="lname" name="lname">
    </div>
    <div>
        <label for="user_email">Email:</label>
        <input type="email" id="user_email" name="user_email">
    </div>
    <div>
        <label for="psword">Password:</label>
        <input type="password" id="psword" name="psword">
    </div>
    <div>
        <input type="submit" value="Submit" />
    </div>
</form>

<script>
    $(document).ready(function () {

        $('form[id="second_form"]').validate({
            rules: {
                fname: 'required',
                lname: 'required',
                user_email: {
                    required: true,
                    email: true,
                },
                psword: {
                    required: true,
                    minlength: 8,
                }
            },
            messages: {
                fname: 'This field is required',
                lname: 'This field is required',
                user_email: 'Enter a valid email',
                psword: {
                    minlength: 'Password must be at least 8 characters long'
                }
            },
            submitHandler: function (form) {
                form.submit();
            }
        });
    });
</script>

@*@section scripts{*@
@*<script type="text/javascript">
        function loadAppointments() {
            //console.log("Entering load function");
            var xhttp = new XMLHttpRequest();
            xhttp.onreadystatechange = function () {
                if (this.readyState == 4 && this.status == 200) {
                    //console.log("Ready and OK");
                    //console.log(this.responseText);
                    var json = JSON.parse(this.responseText);
                    //console.log(json);
                    document.getElementById("test").innerHTML = json.name;
                    //document.getElementById("test").innerHTML = "Full";
                }
            };
            xhttp.open("GET", "https://localhost:44301/api/GetAppointmentItems/", true);
            xhttp.send();
            //console.log("Request sent");
        }
    </script>*@


@*}*@